const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "DRIVER NAME", uid: "driver", sortable: true },
  { name: "EQUIPMENT CODE", uid: "eqCode", sortable: true },
  { name: "TYPE", uid: "type", sortable: true },
  { name: "YEAR", uid: "year" },
  { name: "VIOLATION TYPE", uid: "violation_type" },
  { name: "DATE", uid: "date", sortable: true },
  { name: "COMPLIANCE RATE", uid: "rate", sortable: true },
];

const users = [
  {
    id: 1,
    driver: "Mohammed Ali",
    eqCode: "TRK002",
    type: "Truck",
    year: "2023",
    violation_type: "Speed",
    date: "15/04/2024",
    rate: "85%",
  },
  {
    id: 2,
    driver: "Ali Al-Ahmed",
    eqCode: "VAN003",
    type: "Van",
    year: "2022",
    violation_type: "Overweight",
    date: "07/05/2024",
    rate: "78%",
  },
  {
    id: 3,
    driver: "Omar Hussein",
    eqCode: "BUS004",
    type: "Bus",
    year: "2024",
    violation_type: "Seatbelt",
    date: "20/06/2024",
    rate: "43%",
  },
  {
    id: 4,
    driver: "Khalid Saleh",
    eqCode: "TRK005",
    type: "Truck",
    year: "2021",
    violation_type: "Speed",
    date: "13/07/2024",
    rate: "80%",
  },
  {
    id: 5,
    driver: "Yusuf Ibrahim",
    eqCode: "VAN006",
    type: "Van",
    year: "2023",
    violation_type: "Signal",
    date: "19/08/2024",
    rate: "88%",
  },
  {
    id: 6,
    driver: "Sami Hasan",
    eqCode: "TRK007",
    type: "Truck",
    year: "2022",
    violation_type: "Overweight",
    date: "25/09/2024",
    rate: "75%",
  },
  {
    id: 7,
    driver: "Ahmed Faris",
    eqCode: "BUS008",
    type: "Bus",
    year: "2024",
    violation_type: "Speed",
    date: "30/10/2024",
    rate: "90%",
  },
  {
    id: 8,
    driver: "Faisal Abdullah",
    eqCode: "TRK009",
    type: "Truck",
    year: "2023",
    violation_type: "Seatbelt",
    date: "10/11/2024",
    rate: "84%",
  },
  {
    id: 9,
    driver: "Salim Mohammed",
    eqCode: "VAN010",
    type: "Van",
    year: "2021",
    violation_type: "Signal",
    date: "15/12/2024",
    rate: "39%",
  },
  {
    id: 10,
    driver: "Hassan Ali",
    eqCode: "TRK011",
    type: "Truck",
    year: "2022",
    violation_type: "Overweight",
    date: "22/01/2024",
    rate: "77%",
  },
];

export { columns, users };
